# https://medium.com/@knowbody/circleci-and-zeits-now-sh-c9b7eebcd3c1

machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
  node:
    version: 8.4.0

dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
  pre:
    - yarn global add now

test:
  override:
    - yarn test

deployment:
  production:
    branch: master
    commands:
      - now -t ${NOW_TOKEN}
      - now -t ${NOW_TOKEN} alias
