# https://medium.com/@knowbody/circleci-and-zeits-now-sh-c9b7eebcd3c1

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0

    working_directory: ~/repo

    branches:
      ignore:
        - develop
        - /feature-.*/

    steps:
      - checkout

      - run: yarn
      - run: yarn global add now
      - run: yarn test

      # Deploy production
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then now -t ${NOW_TOKEN}; now -t ${NOW_TOKEN} alias;
            fi
