# https://medium.com/@knowbody/circleci-and-zeits-now-sh-c9b7eebcd3c1

version: 2
jobs:
  build:
    docker:
      - image: ubuntu:14.04
      - image: node:8.4.0

    environment:
      PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

    working_directory: ~/app

    branches:
      ignore:
        - develop
        - /feature-.*/

    steps:
      - checkout

      - run: command: yarn global add now
      - run: command: yarn test

      # Deploy production
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then now -t ${NOW_TOKEN}; now -t ${NOW_TOKEN} alias;
            fi
